appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: yOZOeH6nd4GpIWsdie5r3rXk55R7Oo8GOJlQ4RhS5ErKFl3wA3x+awrJnz+FgWpDr7jOrzGLbshT0wo74X/5dt2ZCu5TBKpV43RZmT7WVi1E+bXQ00HdAARI+FoC3N1nSlOMJA+YgnO3qaErEsLa+HCqOqXB0OtWglm5wULmmZtHob627zS64IEt4IrCUfMOaK2y+WrE6p96ba6jx1dQPALy6uAuoaIdpB7SIUQB60i5gI0C2HsvMBK17Y5R8auYfVcvvhz6DGOsBk9b1Pk982zCs/9Nc5gc99EMeN+28ORCHVLc3CuMs4BTCTp0YorfADG75FldalDTr0JOInlQsW5tiBMsaJjxERHWttKX/cLqZJsRYKZ0SMPcFP7pEPlHURdA3Bo7h4hnfE/CHdx3IBtYAvLZdfj/NfTIKPDeQTNUz05TM8yVORt3o9/x/Ra/hk5UL3x0+677LO9pOPaSDKyxrWhbPMsKG7EQfXV5c6qUbnlM6Tl1N4U2tpy3hjJ8pbm3MtYmoB+nsTO4EvFbFloBhfvjLkuF8/m6ZX0YIplYNSnn0tr5HkrRx5woulNjP++OShRwWxzWOKHuU2OT5T7reqqjnKfByDKTo9fPzV+cQSdACGbvySwB3uZBMQNeVAIZ+jwhp4bdFnwBHy7XYY3ZTmqi0FURTGoITUxGWTM=
conda_forge_output_validation: true
